# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 78b5335a53fe0bae3896ae6868fffe2dce3edb4ebdebef5c2ffd991c7d79e2f5366e7655845c6c11fde7fc043db8316b721275d22a2c895381f4c76d85b16a36

test:
  secret_key_base: eba4b4efc375cf32debd5c734aad28a6919e86d1717bfe559249b1332967c20de6d771198b7d65f5984195c1455fbb6c90dc3d61761801d83fb7fa02d4105b3d

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
